# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa047576fc301d3685e278af00f7742ccd222a2ecbfdec154f25e91fbfdc75e29720f3270000359b7d790aca3f3d3791e64df5570e368fb9f2c5aee54f2aeb93

test:
  secret_key_base: 5e53070358e125f69b89b8f5e1ac0fc9a84d1f7fc9832d33cb6f2a15b4f01aa5a5ea65234f20a5ab9d405e3fed5a5c37eba3e716578520e34e8df9ea14ac5c2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
